name = "cloudflare-ai-assignment"
main = "src/worker.js"
compatibility_date = "2025-09-22"
account_id = "2b2440ce672201763a349589542a4cd1"
workers_dev = true
pages_build_output_dir = "frontend"

[durable_objects]
bindings = [
  { name = "SESSION_DO", class_name = "SessionDO" }
]

[kv_namespaces]
bindings = [
  { binding = "MEMORY_KV", id = "2851a7b4d4684d3f941430b8336e2875" }
]

[ai]
binding = "AI"